development:
  adapter: postgresql
  encoding: unicode
  database: leafy_development
  pool: 5
  host: localhost

test:
  adapter: postgresql
  encoding: unicode
  database: leafy_test
  pool: 5

staging:
  adapter: postgresql
  encoding: unicode
  database: leafy_staging
  pool: 5
  username: leafy
  password: leafy3413

production:
  adapter: postgresql
  encoding: unicode
  database: leafy_production
  pool: 5
  username: leafy
  password: leafy3413
